apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: georgemichael
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: georgemichael
    spec:
      containers:
        - image: "hardik2205/georgemichael"
          imagePullPolicy: Always
          name: georgemichael
          ports:
            - containerPort: 80
